theme: jekyll-theme-cayman
title: "Feminism in lyrics: How women are depicted in recent music"
name: "Slim Kammoun, Xiaoning Yang and Arthur Parmentier"
description: "Data story for ADA 2018"
markdown: kramdown
